-- MySQL Script generated by MySQL Workbench
-- 09/05/14 21:21:39
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fni_ferronorte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fni_ferronorte` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fni_ferronorte` ;

-- -----------------------------------------------------
-- Table `fni_ferronorte`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fni_ferronorte`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `logo_url` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `telefone` VARCHAR(30) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `data_cadastro` DATETIME NOT NULL,
  `usuario_cadastro` INT(11) NOT NULL,
  `data_altera` DATETIME NULL,
  `usuario_altera` INT(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fni_ferronorte`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fni_ferronorte`.`noticia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresa_id` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `posicao` TINYINT NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `data_cadastro` DATETIME NOT NULL,
  `usuario_cadastro` INT(11) NOT NULL,
  `data_altera` DATETIME NULL,
  `usuario_altera` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_noticia_empresa1_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_noticia_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `fni_ferronorte`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fni_ferronorte`.`banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fni_ferronorte`.`banner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresa_id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `banner_url` VARCHAR(100) NOT NULL,
  `posicao` TINYINT NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `data_cadastro` DATETIME NOT NULL,
  `usuario_cadastro` INT(11) NOT NULL,
  `data_altera` DATETIME NULL,
  `usuario_altera` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_banner_empresa1_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_banner_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `fni_ferronorte`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fni_ferronorte`.`orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fni_ferronorte`.`orcamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresa_id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `empresa` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `telefone_fixo` VARCHAR(30) NOT NULL,
  `telefone_celular` VARCHAR(30) NOT NULL,
  `website` VARCHAR(255) NULL,
  `outros` TEXT NULL,
  `data_cadastro` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orcamento_empresa1_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_orcamento_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `fni_ferronorte`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fni_ferronorte`.`estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fni_ferronorte`.`estado_civil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `data_cadastro` DATETIME NOT NULL,
  `usuario_cadasro` INT(11) NOT NULL,
  `data_altera` DATETIME NULL,
  `usuario_altera` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fni_ferronorte`.`escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fni_ferronorte`.`escolaridade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `data_cadastro` DATETIME NOT NULL,
  `usuario_cadastro` INT(11) NOT NULL,
  `data_altera` DATETIME NULL,
  `usuario_altera` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fni_ferronorte`.`trabalhe_conosco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fni_ferronorte`.`trabalhe_conosco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresa_id` INT NOT NULL,
  `estado_civil_id` INT NOT NULL,
  `escolaridade_id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `como_soube` VARCHAR(200) NULL,
  `email` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(10) NULL,
  `sexo` VARCHAR(1) NULL,
  `endereco` VARCHAR(200) NULL,
  `numero` SMALLINT NULL,
  `cep` VARCHAR(9) NULL,
  `complemento` VARCHAR(255) NULL,
  `bairro` VARCHAR(100) NULL,
  `telefone_fixo` VARCHAR(30) NULL,
  `telefone_celular` VARCHAR(30) NULL,
  `telefone_fax` VARCHAR(30) NULL,
  `observacao` TEXT NULL,
  `data_cadastro` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trabalhe_conosco_estado_civil_idx` (`estado_civil_id` ASC),
  INDEX `fk_trabalhe_conosco_escolaridade1_idx` (`escolaridade_id` ASC),
  INDEX `fk_trabalhe_conosco_empresa1_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_trabalhe_conosco_estado_civil`
    FOREIGN KEY (`estado_civil_id`)
    REFERENCES `fni_ferronorte`.`estado_civil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabalhe_conosco_escolaridade1`
    FOREIGN KEY (`escolaridade_id`)
    REFERENCES `fni_ferronorte`.`escolaridade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabalhe_conosco_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `fni_ferronorte`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fni_ferronorte`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fni_ferronorte`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  `data_altera` DATETIME NULL,
  `usuario_cadastro` INT(11) NOT NULL,
  `usuario_altera` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fni_ferronorte`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fni_ferronorte`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria_id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `unidade` VARCHAR(5) NOT NULL,
  `imagem_url` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `data_cadastro` DATETIME NOT NULL,
  `data_altera` DATETIME NULL,
  `usuario_cadastro` INT(11) NOT NULL,
  `usuario_altera` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `fni_ferronorte`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fni_ferronorte`.`pemissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fni_ferronorte`.`pemissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  `data_altera` DATETIME NULL,
  `usuario_cadastro` INT(11) NOT NULL,
  `usuario_altera` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fni_ferronorte`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fni_ferronorte`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pemissao_id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `data_cadastro` DATETIME NOT NULL,
  `usuario_cadastro` INT(11) NOT NULL,
  `data_altera` TIMESTAMP NULL,
  `usuario_altera` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_pemissao1_idx` (`pemissao_id` ASC),
  CONSTRAINT `fk_usuario_pemissao1`
    FOREIGN KEY (`pemissao_id`)
    REFERENCES `fni_ferronorte`.`pemissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fni_ferronorte`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fni_ferronorte`.`carrinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produto_id` INT NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `sessionid` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carrinho_produto1_idx` (`produto_id` ASC),
  CONSTRAINT `fk_carrinho_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `fni_ferronorte`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
